Description: LinnappsUi
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  targetCluster:
    Type: String
    Description: ECS Cluster name within which this application should be run
  dockerTag:
    Type: String
    Description: Docker tag to deploy
  appRoot:
    Type: String
    Description: app root
  proxyRoot:
    Type: String
    Description: proxy root
  databaseHost:
    Type: String
    Description: Database host
  databaseName:
    Type: String
    Description: Database name
  databaseUserId:
    Type: String
    Description: Database user id
  databasePassword:
    Type: String
    Description: Database password
  rabbitServer:
    Type: String
    Description: Rabbit server
  rabbitPort:
    Type: Number
    Description: Rabbit port
  rabbitUsername:
    Type: String
    Description: Rabbit username
  rabbitPassword:
    Type: String
    Description: Rabbit password
  loggingEnvironment:
    Type: String
    Description: Logging Environment
  loggingMaxInnerExceptionDepth:
    Type: Number
    Description: Logging Max Inner Exception Depth
  desiredCount:
    Type: String
    Description: Desired number of instances
  environmentSuffix:
    Type: String
    Description: Environment suffix e.g -int -sys
Resources:
  linnappsUiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: [ "ecs-tasks.amazonaws.com" ]
            Action: [ "sts:AssumeRole" ]
      Path: "/"
      Policies:
      - PolicyName: linnappsUiServices
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:SendMessage
            Resource:
              Fn::ImportValue: logging-queue-arn
  linnappsUiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !GetAtt linnappsUiRole.Arn
      ContainerDefinitions:
      - Name: linnapps-ui
        Cpu: '1'
        Essential: 'true'
        Image: !Sub docker.io/linn/linnapps-ui:${dockerTag}
        PortMappings:
        - ContainerPort: 5050
        Memory: '250'
        LogConfiguration:
          LogDriver: gelf
          Options:
            'gelf-address': 'udp://syslog.linn.co.uk:12201'
            'tag': !Sub linnapps-ui-${dockerTag}-ecs-task
        Environment:
        - Name: DATABASE_HOST
          Value: !Ref databaseHost
        - Name: DATABASE_NAME
          Value: !Ref databaseName
        - Name: DATABASE_USER_ID
          Value: !Ref databaseUserId
        - Name: DATABASE_PASSWORD
          Value: !Ref databasePassword
        - Name: RABBIT_SERVER
          Value: !Ref rabbitServer
        - Name: RABBIT_PORT
          Value: !Ref rabbitPort
        - Name: RABBIT_USERNAME
          Value: !Ref rabbitUsername
        - Name: RABBIT_PASSWORD
          Value: !Ref rabbitPassword
        - Name: APP_ROOT
          Value: !Ref appRoot
        - Name: PROXY_ROOT
          Value: !Ref proxyRoot
        - Name: LOG_AMAZON_SQSQUEUEURI
          Value: !ImportValue logging-queue-url
        - Name: LOG_ENVIRONMENT
          Value: !Ref loggingEnvironment
        - Name: LOG_MAX_INNER_EXCEPTION_DEPTH
          Value: !Ref loggingMaxInnerExceptionDepth
        - Name: awsRegion
          Value: !Ref AWS::Region
  linnappsUiService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref targetCluster
      DesiredCount: !Ref desiredCount
      TaskDefinition: !Ref linnappsUiTaskDefinition
      Role: ecsServiceRole
      LoadBalancers:
      - ContainerName: linnapps-ui
        ContainerPort: 5050
        TargetGroupArn:
          Fn::ImportValue:
            !Sub "linnapps-ui-target-group-arn${environmentSuffix}"